### PR TITLE
Added op AND_INDIRECT_Y

### PR DESCRIPTION
**Pull request by Mark-Platts**
Added AND with indirect y address mode.

I need to make sure I 100% understand the mode and then test it. Though tiredness has just hit me so I think I'll call it for this evening.

### CODE REVIEW

**Comment by Mark-Platts** [comment]
I think indirect Y might be a little more complicated than I first realised. It seems the zero page word that you add Y to also has to wrap around before Y is added.

That means the only difference between indirect x and y is whether the register is added before or after the word from zero page is retrieved.

I'm guessing the page boundary check still happens before and after the y is added, since that addition can take us out of page zero, unlike the x version.

**Comment by Mark-Platts** [comment]
Am I allowed to just add a Byte to a Word, or do I need to do something to the Byte first?

**Comment by colin-broderick** [comment]
If you add two different types then C++ will implicitly convert the smaller type to the bigger type, if it can. So if you write
```
Byte a = 3;
Word b = 4;
Word c = a + b;
```
then `a` will be implicitly converted to a Word before doing the add. Converted inline, that is, so the original variable `a` is unaffected. If you want to be completely explicit - perhaps because you're not completely sure what C++ will do in some situation - you can cast it first.
```
Byte a = 3;
Word b = 4;
Word c = (Word)a + b;
```
That is C style casting. C++ has more advanced casting options but I haven't done my reading on them yet. This will work in this context.

**Comment by Mark-Platts** [comment]
Alright thanks. I'm just testing it now so I'll let you know if it works without casting.

**Comment by colin-broderick** [comment]
C++ is allowed to do exactly one implicit conversion, and there must be a well-defined way to do that conversion. If a conversion would require more than one step or there is more than one valid way to do it, C++ won't try. In that case you'll get some warning or error.

**Comment by colin-broderick** [comment]
By the way this is probably related to the `address + 1` problem we were having. The default type of the literal `1` is an int, I think, so C++ will have implicitly converted the `address` to an int, then add them. Because the result never gets stored in a Byte or anything it never gets to overflow as we might like.

Unrelated, but worth knowing: the default type of a number like `0.268` is double. If you want a float it's good practice to write `0.268f`. That tells the compiler it's a float (32 bit) not double (64 bit). In most situations double is preferable.

**Comment by Mark-Platts** [comment]
Ah ok ,all very much worth noting.

I've been thinking about the functions to generalise this stuff btw. I'm thinking we have a set of functions to get data via the different address modes. So get_data_indirect_x with the appropriate arguments for example. I think page boundary checking would need to be their own separate functions for each of the required addressing modes too. So a function that just returns a bool if page boundary is crossed.

Do you agree that that sounds worthwhile? I'd like to start working on them this evening unless you have any better ideas.

**Comment by colin-broderick** [comment]
I do agree it's worthwhile, and I was thinking along the same lines. I haven't started doing it because I wasn't sure if there would be any weird edge cases to do with number of cycles.

Is it the case, for example, that get_data_indirect_x should always take the same base number of cycles, and the possible addition of one for page crossing is the only variation?

**Comment by Mark-Platts** [comment]
Indirect x only ever takes 6 cycles. If I understand it correctly, it's because the addition of x with the first byte, and then the retrieval of the zero page word, all happen in such a way that the zero page cannot be left.

Indirect y on the other hand takes 5, but the y is added after the zero page address lookup and doesn't put any restraints on whether it changes the page number or not.

Now that I've got a feel for it. I've noticed the extra cycle is only there when the addition of x or y could cause the page number to change. So it should just be a case of giving a function the first address and x or y and seeing if the after address is on a new page. Then returning the bool.

If I had to guess why any of this happens. I'd say it's because when we know that there is no possibility of changing page number. Everything can be done with Bytes. Otherwise a second Byte needs to be retrieved by the cpu to update the high Byte of the address. If that makes sense.

**Comment by Mark-Platts** [comment]
All working as it should :) ready to merge.

**Comment by Mark-Platts** [comment]
Actually had to get a pen and paper out for that one :P

**Comment by colin-broderick** [comment]
Haha, I do lots of programming on paper. Some people in the office look at me funny but there's no doubt it's useful.

**Comment by colin-broderick** [comment]
BTW I'm going to be difficult and make it a rule that I won't merge anything until the WIP is removed from the name :)

**Comment by Mark-Platts** [comment]
I can't complain. I totally forgot it was even in there.

**Pull request merged**
