### PR TITLE
Finished adding LDA instructions

### PR DESCRIPTION
**Pull request by colin-broderick**
Adding the remaining LDA instructions, and moved LDA_INDIRECT_X to be grouped with the others.

### CODE REVIEW

**Review by Mark-Platts — COMMENTED** [review]
Seems fine for the most part. I'm not sure if I've found an issue with the LDA_INDIRECT_X though.

It's my understanding (backed up by the formula [here](https://wiki.nesdev.com/w/index.php/CPU_addressing_modes)) that both bytes of the target address need to come from the zero page. So when the get_word is used on line 193, it would have to cater for the second byte falling outside of the zero page by wrapping it around.

It's certainly the trickiest of the address modes. It might be worth making a special get_word_zeropage function for when we need to do this.

I'm not 100% sure, but I think replacing indirect_address on line 193 with (indirect_address % 256) should do it. Let me know what you think.

Everything else looks fine though!

**Comment by colin-broderick** [comment]
My understanding was that you only wrap at the first level of indirection. So the first thing I read is a byte address (i.e. zero page address) and then add X to it, with wrapping. That all occurs on line 188.

We are now pointing at the lowest byte of the next address we need to read from. Reading a full word gives a full address from where we fetch data. That full address is what is read on line 193.

We then grab the single byte from that full word address. I haven't seen anything to indicate that the actual data byte must come from the zero page. The address table is held on the zero page but the actual data those addresses point to can be anywhere, as far as I can tell.

Read the 'indexed indirect' section here http://www.obelisk.me.uk/6502/addressing.html#IDX and tell me what you think.

I will spend a little time pondering that formula. I'm glad you agree it's the trickiest one. It feels like it really needn't be, but is being over explained.

**Comment by colin-broderick** [comment]
Put another way, the thing stored on zero page is a table of Word addresses. All the complexity is about discerning that Word address, but those addresses themselves can point to anywhere.

**Comment by colin-broderick** [comment]
peek(
  peek(
    (arg + X) % 256
  )
  +
  peek(
    (arg + X + 1) % 256
  )  * 256
)

The second inner peek here is multiplied by 256, so it becomes the page number, while the first is the address within the page. This is reading two bytes from the zero page, and the second of the bytes the page number of the address from where we get the real data.

Do you agree?

**Comment by colin-broderick** [comment]
I've just realized the problem. You're asking what happens if the first byte happens to be at the end of the page. In that case reading a word ignores the need to wrap. I think you're right.

**Comment by Mark-Platts** [comment]
I was about to reply :P but yes you spotted what I meant. When get_word reads its second byte, that also has to come from the zero page. The formula does this by wrapping both bytes using a modulus. So for the second byte we get (arg + X + 1) % 256

**Comment by Mark-Platts** [comment]
To clean up that ugliness, I do think a special get_word function that takes care of the wrapping internally could be worthwhile.

**Comment by colin-broderick** [comment]
Cool, nice work spotting the error. I'll give it some thought and probably push a change later today.

**Comment by colin-broderick** [comment]
I've realized that the function with signature

Word CPU::get_word(Memory& memory, const Byte address)

already does this, unintentionally. Will fix that and add a new, more explicitly named function to do what it currently does.

**Comment by colin-broderick** [comment]
I think it's ready now

**Comment by Mark-Platts** [comment]
Looks good to me. I see now what was wrong with the old get_word too. Good spot.

**Pull request merged**
