### PR TITLE
AND with indirect-x

### PR DESCRIPTION
**Pull request by Mark-Platts**
Added AND with indirect x address mode. It's still confusing but I think I'm getting the hang of it.

Page 6 of this document really helped me get my head around them all yesterday: http://archive.6502.org/datasheets/mos_6501-6505_mpu_preliminary_aug_1975.pdf

I'll try and figure out how to test it so that we can check our understanding before doing too many of these.

### CODE REVIEW

**Comment by colin-broderick** [comment]
Sounds good. The explanation there appears to gel with our understanding as of yesterday.

I'd still like to look into the possibility of abstracting the addressing modes into functions if possible, so we only have to work it out once!

**Comment by Mark-Platts** [comment]
I did plan on having a go at that when I sat down earlier. But there turned out to be a bit more to consider than I originally thought. If it hasn't been done by one of us by Thursday, shall we figure it out together?

**Comment by Mark-Platts** [comment]
Tested it quite thoroughly and so far it's good. I'm just going to do one more test to make sure that the wrap around does what it should.

**Comment by Mark-Platts** [comment]
I'm afraid there seems to be a problem and I think I've isolated it to the get_word_zpg_wrap function.

If you look at the test in the system, I've set it up so that once X is added, it should get the low address byte from 0xff which it does. It should then wrap around and get the high address byte from 0x00, but it's actually getting it from 0x100. I'm going to take a look at the function and see if I can spot what's wrong.

**Comment by Mark-Platts** [comment]
I don't want to mess with stuff you wrote without asking first:

For the get_word_zpg_wrap function. Should it be Byte in the brackets instead of Word? Since val1 and 2 are bytes that then get conjoined?

**Comment by colin-broderick** [comment]
That's annoying. Since the data type of address is Byte it should overflow automatically. I guess I've not understood how that works. We can of course resolve it by doing the wrap manually if necessary.

**Comment by Mark-Platts** [comment]
Did you want to tackle that or shall I?

**Comment by colin-broderick** [comment]
That shouldn't matter, because the address+1 is evaluated first, and that's the part that we need to wrap. You could do

(address + 1) % 256

and that word guarantee the wrap. I would have expected that to be automatic since address is of type Byte but I will have do to some investigating.

However, all that is irrelevant in the face of experiment! You've been a lot more careful on these so I will defer to your tests. Go ahead and tackle it if you'd like to.

**Comment by colin-broderick** [comment]
The reason for casting to word is to make sure they're both 16-bit types before the merge. It's probably only necessary for one of the components, but it shouldn't hurt anything applying it to both.

**Comment by Mark-Platts** [comment]
Since it's such an easy fix, I'll just pop it in this branch. I'll do a few more tests and come back.

I feel like we need to make sure we have gotten these address modes perfect before we start making general functions for them. Hence the testing.

**Comment by Mark-Platts** [comment]
That worked and everything functions perfectly now :) I think it's ready for merge.

**Comment by colin-broderick** [comment]
Ok cool. Will take a look.

I did a little investigation and the automatic overflow doesn't work in every context. I think here because the value `address+1` is never stored it doesn't work, but if I had done (e.g.) `Byte addr1 = address + 1`, and then proceeded to do the other parts, it would have worked.  Maybe!

**Comment by Mark-Platts** [comment]
Interesting.

After I've finished with the AND operations, I'm going to make a function for getting data via indirect x. I'll use the code we just merged as a basis since I've thoroughly tested it.

I'll then have a look at the others. My main worry is how to deal with ones where you test for a page boundary, I think we might also need a function that tests for that separately.

**Pull request merged**
